# Generated by Django 4.2.9 on 2025-07-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='month',
            field=models.DateField(blank=True, null=True, verbose_name='Mes'),
        ),
    ]
