# Generated by Django 4.2.9 on 2025-07-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(blank=True, choices=[('pichincha_card', 'Tarjeta Pichincha'), ('produbanco_card', 'Tarjeta Produbanco'), ('cash', 'Efectivo')], max_length=100, null=True, verbose_name='Tipo'),
        ),
    ]
