# Generated by Django 4.2.9 on 2026-03-16 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_expense_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('type', models.CharField(blank=True, choices=[('debit', 'debit'), ('credit', 'credit')], max_length=100, null=True, verbose_name='Tipo')),
                ('cut_off_day', models.IntegerField(default=1, verbose_name='Día de corte')),
                ('payment_day', models.IntegerField(default=1, verbose_name='Día de pago')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.card', verbose_name='Tarjeta'),
        ),
    ]
