# Generated by Django 4.2.9 on 2026-03-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_card_expense_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico Asociado'),
        ),
        migrations.AddField(
            model_name='card',
            name='mail_receipt',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico para recibos'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(blank=True, choices=[('card', 'Tarjeta'), ('cash', 'Efectivo'), ('other', 'Otro')], max_length=100, null=True, verbose_name='Tipo'),
        ),
    ]
