# Generated by Django 4.2.9 on 2026-03-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_card_mail_card_mail_receipt_alter_expense_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='mail_receipt',
        ),
        migrations.AddField(
            model_name='card',
            name='mail_subject',
            field=models.CharField(blank=True, null=True, verbose_name='Asunto del correo'),
        ),
    ]
