# Generated by Django 4.2.9 on 2026-03-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_card_mail_receipt_card_mail_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='Color'),
        ),
    ]
