# Generated by Django 4.2.9 on 2026-03-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_card_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='month',
        ),
    ]
